### ISSUE TITLE
image path doesn't work

### ISSUE THREAD

**Issue by FriedrichLeineweber** [SuperPrower/i3lock-fancier#8]
Hi,

image_path = /home/fritz/Bilder/Wallpaper.jpg
in the config.ini doesn't seem to work, or am I doing something  wrong here?

**Comment by SuperPrower** [comment]
https://github.com/i3/i3lock/issues/68

Convert your image to png or use some other image.

**Comment by FriedrichLeineweber** [comment]
Worked, thanks
