### ISSUE TITLE
Add the path variable as argv input parameters of your application

### ISSUE THREAD

**Issue by informaterian** [SuperPrower/i3lock-fancier#9]
https://github.com/SuperPrower/i3lock-fancier/blob/46299b7103f913761beb144d5a1ca59fe682ba35/i3lock.c#L872

This would allow for example to add a default configuration to `/etc/i3lock-fancier` or `/usr/share/i3lock-fancier` during pacaur installation.

**Comment by SuperPrower** [comment]
I don't have time to work on this fork anymore. It works for me (and few other people) as intended, so unfortunately I am not planning on making any enhancements. Also, I don't really understand what are you proposing, sorry.

It seems you are planning on distributing this fork in the AUR? I wouldn't really recommend doing that for many reasons, including one that this fork is many, many commits behind original i3lock and i3lock-color projects, and that i3lock-color now seems to have keyboard layout support.
